### ISSUE TITLE
Showing different Code

### ISSUE THREAD

**Issue by sakul-budhathoki** [jaesung2061/anvel#1]
Show different  code when "VIew Page Source"  at  " localhost:3000" . I expect to see app.component.html.

**Comment by jaesung2061** [comment]
When you click view page source, it shows only the initial document that was received. It doesn't show content that was loaded (using AJAX) after the initial page load.

To view all content, go to the developer console. Right click anywhere on the document and click "Inspect Element" and go to the "Elements" tab. You will see the HTML you were looking for.
