### ISSUE TITLE
JWT Token not beeing stored

### ISSUE THREAD

**Issue by rqyrku** [jaesung2061/anvel#11]
Hi, I'm having a problem where the token generated by JWT (and any other asset by the way) is not stored in cache. Login works correctly but when I refresh the page I'm logged out immediately, saying that the cached token was not found. Could it be that the cache isn't enabled although I specified it in the .env?

**Comment by jaesung2061** [comment]
You shouldn't be using cache to store tokens. Can you try logging in and showing me the localStorage variable?

**Comment by rqyrku** [comment]
I found the token in the local storage the problem is that after refreshing the page the token is deleted. I found the problem is related to the code in app.component.ts it when it checks for the token on init it deletes it on no event. Removing that line works well.

**Comment by jaesung2061** [comment]
Ok I've committed the fixes with a new minor release. Thanks for the heads up.

**Comment by jaesung2061** [comment]
Oh I should also let you know that the reason the token was being removed was that the API endpoint was returning data in an unexpected format.

Expected format:

```
{
    data: {user: object}
}
```

Actual:

```
{
    user: object
}
```
