### ISSUE TITLE
Edited text doesn't change after refresh

### ISSUE THREAD

**Issue by ranggaperwiratama** [jaesung2061/anvel#13]
I've followed your routing documentation on http://anvel.io/docs/routing. 

Navigating to the Route.
Add this link anywhere accessible.

<a [routerLink]="['/contact']">Contact</a>
Note: Don't forget to inject ROUTER_DIRECTIVES into the component.
Refresh the page and click on the link.

I've been refreshing 1000 times, nothing happened. Noob here, please help.

**Comment by jaesung2061** [comment]
Hey, you need to run command `webpack` to recompile your assets after you make changes. But obviously you don't want to do that every time. So run the file watchers by running `webpack --watch`. Any time you make changes, the builder will automatically compile the assets for you and refresh the page at http://localhost:3000.

**Comment by jaesung2061** [comment]
If you are still having this issue, feel free to reopen.
