### ISSUE TITLE
some error while run webpack

### ISSUE THREAD

**Issue by stojankukrika** [jaesung2061/anvel#14]
Hi,
When I follow steps to install npm I got some erros, I ignore them and try to run webpack but then I get these errors:

ERROR in D:\xampp\htdocs\anvel\node_modules\@ng-bootstrap\ng-bootstrap\buttons\radio.d.ts
(11,14): error TS1005: '=' expected.

ERROR in D:\xampp\htdocs\anvel\node_modules\@ng-bootstrap\ng-bootstrap\buttons\radio.d.ts
(11,22): error TS1005: ';' expected.

ERROR in D:\xampp\htdocs\anvel\node_modules\@ng-bootstrap\ng-bootstrap\buttons\radio.d.ts
(11,14): error TS2304: Cannot find name 'disabled'.

ERROR in ./angular/styles.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./styles/bootstrap/bootstrap-flex.scss in D:\xampp\htdocs\anvel\angular
 @ ./angular/styles.ts 8:0-65

I use windows 7, xampp on php 7, last version nodejs 7.4. Can you help me?

**Comment by jaesung2061** [comment]
For the following error:

    ERROR in ./angular/styles.ts
    Module not found: Error: Cannot resolve 'file' or 'directory' ./styles/bootstrap/bootstrap-flex.scss in D:\xampp\htdocs\anvel\angular
    @ ./angular/styles.ts 8:0-65

It looks like one of the scripts failed because you are running on Windows. Copy `./node_modules/bootstrap` to `./angular/styles/bootstrap`.

For these errors:

```
ERROR in D:\xampp\htdocs\anvel\node_modules@ng-bootstrap\ng-bootstrap\buttons\radio.d.ts
(11,14): error TS1005: '=' expected.

ERROR in D:\xampp\htdocs\anvel\node_modules@ng-bootstrap\ng-bootstrap\buttons\radio.d.ts
(11,22): error TS1005: ';' expected.

ERROR in D:\xampp\htdocs\anvel\node_modules@ng-bootstrap\ng-bootstrap\buttons\radio.d.ts
(11,14): error TS2304: Cannot find name 'disabled'.
```

Open an issue with https://github.com/ng-bootstrap/ng-bootstrap. If the `styles` issue is resolved, please close this issue.

**Comment by stojankukrika** [comment]
Do you think that will work on some linux or mac osx?Can you try and give me info did that works?Please, sir.

**Comment by jaesung2061** [comment]
The error that happened because you are on Windows can be fixed by manually moving `node_modules/bootstrap/scss` to `angular/styles`. Then rename the `scss` folder to `bootstrap` in `angular/styles`.

The other issue must be opened with the other repository since this is not an issue with Anvel specifically.

**Comment by stojankukrika** [comment]
Yes, I understand that. But can you tell me which OS is OK to I can install and test this repo? Linux or Mac OSX?Can you tell did you test it and in which operation system?

**Comment by jaesung2061** [comment]
It works on both OSX and Linux.

**Comment by stojankukrika** [comment]
OK. I will try tomorrow and write you a comment did it's works. TNX.

**Comment by stojankukrika** [comment]
am get the same errors in macosx also when run weback.

**Comment by jaesung2061** [comment]
Delete the `node_modules` folder and try running `npm install`

**Comment by stojankukrika** [comment]
It's the same. Can you upload fresh installation and send me a link?

**Comment by jaesung2061** [comment]
I think it may have to do with breaking changes in the npm packages. I'll have to take a look into them this weekend.

**Comment by stojankukrika** [comment]
Thank you bro!you are THE BEST!!!

**Comment by stojankukrika** [comment]
Hi,did you maybe find what is the problem?

**Comment by jaesung2061** [comment]
I can't seem to reproduce the issue. Are the errors exactly the same as before? Check `angular/styles` and see if there is a `bootstrap` directory there.

What is the environment you are currently working in? OS? Node version?

**Comment by stojankukrika** [comment]
Hi. I now try again. Delete everything and go step by step. I get some errors during npm install and webpack, you can find it below. But when run php artisan serve it's shows something to me (I hope that is OK-it the same as http://anvel.io).

Can you please tell me how to deploy to some public hosting server?

This is when I start npm install:
![1](https://cloud.githubusercontent.com/assets/10199584/21753144/9996b106-d5e6-11e6-990f-c30b26eb2391.jpg)
And when run webpack:
![3](https://cloud.githubusercontent.com/assets/10199584/21753143/90179e2e-d5e6-11e6-81f5-0f3d12b78737.png)

**Comment by stojankukrika** [comment]
I also try to update typescript to version 2.1.4(last) based on this issue: https://github.com/ng-bootstrap/ng-bootstrap/issues/1175 but have another errors :(

![4](https://cloud.githubusercontent.com/assets/10199584/21753213/5f43f78c-d5e8-11e6-8ee0-a8afd42cc873.png)

**Comment by jaesung2061** [comment]
I'm working on the fixes, hang in there.

**Comment by stojankukrika** [comment]
thank you bro!

**Comment by jaesung2061** [comment]
Ok, for now this fix will have to do.

Delete your `node_modules` directory, replace your `package.json` with this one: https://gist.github.com/jaesung2061/d05f835d6b9c910fe3d96866e5d8ac45.

Run `npm install` and `npm run webpack`. It will show a lot of errors but the build will still work as intended.

**Comment by jaesung2061** [comment]
Oh and go to `webpack/webpack.common.js` and comment out this line:

        preLoaders: [
            // {
            //     test: /\.ts$/,
            //     loader: "tslint"
            // }
        ],

**Comment by stojankukrika** [comment]
hm... now I get this error while run npm run webpack:

typings\browser\ambient\node\index.d.ts
(426,11): error TS2430: Interface 'NodeBuffer' incorrectly extends interface 'Uint8Array'.
  Types of property 'fill' are incompatible.
    Type '(value: any, offset?: number, end?: number) => Buffer' is not assignable to type '(value: number, start?: number, end?: number) => this'.
      Type 'Buffer' is not assignable to type 'this'.

**Comment by jaesung2061** [comment]
Yes it'll give you errors but it should have compiled regardless. Run `php artisan serve` and go to localhost:8000

**Comment by stojankukrika** [comment]
Yes. It's shows errors but it's works! Thank you bro!
