### ISSUE TITLE
installing issue

### ISSUE THREAD

**Issue by ProxyAi** [jaesung2061/anvel#15]
after running the command webpack I get the following errors

![image](https://cloud.githubusercontent.com/assets/11992984/21683858/17441c42-d353-11e6-838c-9b4b613068a9.png)

$ npm -v
4.0.5
$ nodejs -v
v7.4.0

**Comment by jaesung2061** [comment]
I will be providing a fix with a new release. Some of the packages were out of date.

**Comment by vjaro** [comment]
@jaesung2061 i'm also encountering this issue. Hopefully this will get resolved

**Comment by insertkoens** [comment]
I had this problem today. Using node v4.2.4 and angular 2.4.10 made it work, but browsersync wont stop loading.

**Comment by corientdev** [comment]
+1

**Comment by jaesung2061** [comment]
Project was reworked. Issue no longer relevant.
