### ISSUE TITLE
How to final publish on public shared hosying?

### ISSUE THREAD

**Issue by stojankukrika** [jaesung2061/anvel#16]
Hi,
Can you tell me when I finish application,how do I publish it into publish hosting?Only copy files using ftp?Which one I need and how to copy to server that everything works?Tnx for this great start package!

**Comment by jaesung2061** [comment]
What version of php? Apache or Nginx?

**Comment by stojankukrika** [comment]
I think on hostgator server with php 7.0 extension.

**Comment by jaesung2061** [comment]
Try looking on their website for a guide to uploading the website. I am not
familiar with that hosting company. There is already an .htaccess file you
can use in `public` directory of your project.

**Comment by stojankukrika** [comment]
ok. tnx, maybe it will be helpful.

**Comment by jaesung2061** [comment]
Closed for inactivity
