### ISSUE TITLE
How to close error alert?

### ISSUE THREAD

**Issue by stojankukrika** [jaesung2061/anvel#18]
How to close error alert who have close button?
![login](https://cloud.githubusercontent.com/assets/10199584/22169578/6caabe88-df75-11e6-9e33-b11e9fab9dbb.png)

This I am change in login component:
 <ngb-alert type="danger" [dismissible]="false" *ngIf="error">
        <span>The email/password you provided does not match our records.</span>
    </ngb-alert>

to:
 <ngb-alert type="danger" [dismissible]="true" *ngIf="error">
        <span>The email/password you provided does not match our records.</span>
    </ngb-alert>

**Comment by jaesung2061** [comment]
Project was reworked. Issue no longer relevant.
