### ISSUE TITLE
How to submit get params to api?

### ISSUE THREAD

**Issue by stojankukrika** [jaesung2061/anvel#19]
Hi,
How to send get params over api? I ty to send string and URLSearchParams object as search 
return this.api.get('endpoint', {search: params, headers: this.options.headers}).do( ... but it's didn't work :( can you help me?

**Comment by sakul-budhathoki** [comment]
options={data: {paginate:15,search:null,sort:null,sortby:null} };
 this.api.get('item',this.options)
