### ISSUE TITLE
Running anvel on wamp (Windows 8.1)

### ISSUE THREAD

**Issue by chrzysztof** [jaesung2061/anvel#20]
I tried to run anvel on wamp server in Windows. I upadated PHP version (I have version 7.0.15), but in console I have a bug :

`rerquire_once(): Failed opening required 'C:\wamp64\www\beauty-app\anvel\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear' in C:\wamp64\www\beauty-app\anvel\bootstrap\app.php on line 3 `

There is a screen: https://imgur.com/FMttWhL

I looked for a autoload.php file in my project directory, but I can't find it. What should I do to run my project?

**Comment by jaesung2061** [comment]
The `autoload.php` file should be within the `vendor` directory. Have you ran `composer install`?

**Comment by chrzysztof** [comment]
Ok. I solved a problem. 
After updating PHP in wamp I had to update composer.
