### ISSUE TITLE
Error 404, when I try to logout/delete token 

### ISSUE THREAD

**Issue by chrzysztof** [jaesung2061/anvel#21]
I try on my localhost (Windows 8.1, wamp) to logout by click button, but in concole I can see error 404:
https://i.imgur.com/meeizpu.png

My logout function in component.ts:
```
public logoutUser() {
        this.auth.logout().subscribe(
            () => {
                console.log("Logout success.");       
            },
            (error) => {
                this.error = true;
                console.error(error);
            });
    }
```

My logout function in component.html:
`<button (click)="logoutUser()">Wyloguj</button>`

What is the propper way to create component with content available only for logged in users with "Logout button"

**Comment by jaesung2061** [comment]
Project was reworked. Issue no longer relevant.
