### ISSUE TITLE
Errors on installing

### ISSUE THREAD

**Issue by MarcelFranken** [jaesung2061/anvel#22]
Hi there,

i'm on a Debian Wheezy machine with NodeJS v6.10.0 and npm 4.2.0.
After the npm install command i get the following:

> -- UNMET PEER DEPENDENCY zone.js@0.6.26
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN @angular/http@2.4.8 requires a peer of rxjs@^5.0.1 but none was installed.
> npm WARN @angular/router@3.4.8 requires a peer of rxjs@^5.0.1 but none was installed.
> npm WARN @angular/core@2.4.8 requires a peer of rxjs@^5.0.1 but none was installed.
> npm WARN @angular/core@2.4.8 requires a peer of zone.js@^0.7.2 but none was installed.
> npm WARN anvel@1.0.0 No repository field.

How can i solve this?

Thank you!

**Comment by jaesung2061** [comment]
I'm guessing it's your node version. Try updating node, see if that fixes it.

**Comment by MarcelFranken** [comment]
Hi there,

now, when i run webpack i get this error:

> ts-loader: Using typescript@2.2.1 and D:\anvel\tsconfig.json
> Hash: 08900671204a4b62b194
> Version: webpack 1.14.0
> Time: 7716ms
>                Asset     Size  Chunks             Chunk Names
>       main.bundle.js  3.01 MB       0  [emitted]  main
>     styles.bundle.js   212 kB       1  [emitted]  styles
>     vendor.bundle.js   282 kB       2  [emitted]  vendor
>   main.bundle.js.map  3.62 MB       0  [emitted]  main
> styles.bundle.js.map   275 kB       1  [emitted]  styles
> vendor.bundle.js.map   352 kB       2  [emitted]  vendor
>     + 407 hidden modules
> 
> ERROR in D:\anvel\typings\browser\ambient\node\index.d.ts
> (426,11): error TS2430: Interface 'NodeBuffer' incorrectly extends interface 'Uint8Array'.
>   Types of property 'fill' are incompatible.
>     Type '(value: any, offset?: number, end?: number) => Buffer' is not assignable to type '(value: number, start?: number, end?: number) => this'.
>       Type 'Buffer' is not assignable to type 'this'.

Any solution?

Thanks!

**Comment by jaesung2061** [comment]
It should actually work at this point. Run `php artisan serve` and go to http://localhost:8000

**Comment by MarcelFranken** [comment]
Oh, ok..
Yes it works like a charme, but can you tell me why this error comes up?

**Comment by jaesung2061** [comment]
I'm not sure, try taking a look at this issue: https://github.com/typings/typings/issues/554. It looks like the same issue as the one your having.
