### ISSUE TITLE
When I install , running npm install  in my project folder , it shows following message

### ISSUE THREAD

**Issue by timloo0710** [jaesung2061/anvel#26]
C:\Users\synct\projects\myLumenNg>npm install

> anvel@1.0.0 postinstall C:\Users\synct\projects\myLumenNg
> typings install && npm run bootstrap

├── moment
├── es6-shim (ambient)
├── jasmine (ambient)
└── node (ambient)

> anvel@1.0.0 bootstrap C:\Users\synct\projects\myLumenNg
> if [ ! -d "angular/styles/bootstrap" ]; then cp -R node_modules/bootstrap/scss angular/styles/bootstrap; fi

這個時候不應有 !。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anvel@1.0.0 bootstrap: `if [ ! -d "angular/styles/bootstrap" ]; then cp -R node_modules/bootstrap/scss angular/styles/bootstrap; fi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the anvel@1.0.0 bootstrap script 'if [ ! -d "angular/styles/bootstrap" ]; then cp -R node_modules/bootstrap/scss angular/styles/bootstrap; fi'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the anvel package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     if [ ! -d "angular/styles/bootstrap" ]; then cp -R node_modules/bootstrap/scss angular/styles/bootstrap; fi
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs anvel
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls anvel
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\synct\AppData\Roaming\npm-cache\_logs\2017-04-06T03_19_07_874Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.10 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN @angular/http@2.4.10 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/router@3.4.10 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN anvel@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anvel@1.0.0 postinstall: `typings install && npm run bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the anvel@1.0.0 postinstall script 'typings install && npm run bootstrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the anvel package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && npm run bootstrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs anvel
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls anvel
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\synct\AppData\Roaming\npm-cache\_logs\2017-04-06T03_19_07_960Z-debug.log

--------------------------
My envirnment
OS: win10
node:v7.2.0
npm:4.4.4

Best Regards

**Comment by jaesung2061** [comment]
If you are on Windows, you must manually copy node_modules/bootstrap/scss to angular/styles/scss and rename the scss directory to bootstrap. Run webpack after copying.

**Comment by jaesung2061** [comment]
Project was reworked. Issue no longer relevant.
