### ISSUE TITLE
Angular with Laravel tutorial

### ISSUE THREAD

**Issue by newkillerbeast2017** [jaesung2061/anvel#27]
@jaesung2061 Can you please create a tutorial on how to integrate Angular with Laravel? Might be very useful for future.

**Comment by newkillerbeast2017** [comment]
@jaesung2061 any help?

**Comment by jaesung2061** [comment]
Sorry, I don't have time to make tutorials right now.

**Comment by newkillerbeast2017** [comment]
Okay.
