### ISSUE TITLE
You have to be inside an angular-cli project in order to use the build command.

### ISSUE THREAD

**Issue by MohanadI** [jaesung2061/anvel#29]
Hello ,

after I type " ng build --watch " this error appears !

any suggestions .

Thank you .

**Comment by jaesung2061** [comment]
Are you in the root project directory? Not the `angular` directory, but the Lumen root directory.

**Comment by serkandyck** [comment]
if you use ng build command root project directory in direct you get error You have to be inside an angular-cli project in order to use the build command. But if u run npm run build Everything OK.

**Comment by jaesung2061** [comment]
Apologies. I had the wrong npm package for Angular CLI.

It is `npm install -g @angular/cli`, not `npm install -g angular-cli`

**Comment by MohanadI** [comment]
Thanks now its working perfectly .
