### ISSUE TITLE
Page loads forever

### ISSUE THREAD

**Issue by re1naldo** [jaesung2061/anvel#5]
I have just finished installing this. After I executed `npm start`, it redirected me to `localhost:3000`, but that page kept loading and finally gave error: 
`The localhost page isn’t working. localhost didn’t send any data.`

The web server was already running and I could run the other applications there. What should I check here?

**Comment by jaesung2061** [comment]
Are you running php artisan serve? Check what port it's running on when you
execute the command.

**Comment by re1naldo** [comment]
Running `php artisan serve` would give an error:
`PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in /var/www/html/anvel/bootstrap/app.php on line 3`

The port seemed to be correct, no?

```
[BS] Proxying: http://localhost:8000
Local: http://localhost:3000
External: http://10.193.203.31:3000
UI: http://localhost:3001
UI External: http://10.193.203.31:3001
```

**Comment by jaesung2061** [comment]
Can you copy and paste line three of `bootstrap/app.php`?

**Comment by re1naldo** [comment]
`const APP_ROOT = __DIR__.'/../';`

I haven't made any changes to the original files.

**Comment by jaesung2061** [comment]
What version of php are you using?

**Comment by re1naldo** [comment]
5.5.9-1ubuntu4.17

**Comment by jaesung2061** [comment]
Try upgrading your php version.

**Comment by re1naldo** [comment]
`npm start` still  gave the same result after upgrading PHP, but I can use `php artisan serve` now. Thanks for your support.

**Comment by insertkoens** [comment]
I'm having this issue with php 6.25. Access via :8000 and :3001 both working, but :3000 keeps loading. Everything else seems to be working fine, except for browsersync.

UPDATE:
Looks like ive finally got it to work using 127.0.0.1 instead of localhost both in .env and php artisan serve --host:127.0.0.1
