### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by JustinRvt** [jaesung2061/anvel#6]
Hello,

First of all, thanks for your project, I was looking for a PHP micro framework and here are you with Lumen+Angular2.
I followed your instructions but I always get the same error :

`Parse error: syntax error, unexpected '.', expecting ',' or ';' in /var/www/html/bootstrap/app.php on line 3`

But it looks ok to me :

```
<?php

const APP_ROOT = __DIR__.'/../';

require_once __DIR__.'/../vendor/autoload.php';

try {
    (new Dotenv\Dotenv(__DIR__.'/../'))->load();
} catch (Dotenv\Exception\InvalidPathException $e) {
    //
}
```

(I tried on 2 different servers)

If you have any clue, I'd take it.
Thanks a lot!

**Comment by jaesung2061** [comment]
Hey this issue is the same as #5. You need to upgrade your PHP version to >=5.5.9.

**Comment by JustinRvt** [comment]
You MIGHT laugh, but I had exactly this version. Upgrading to 5.6 just did the trick.
Can't wait to play around with your work. 

Thank you so much Jaesung

**Comment by jaesung2061** [comment]
Nice, I should update the composer.json file to reflect the correct
minimum. And feel free to make contributions if you'd like.
