### ISSUE TITLE
Update core packages

### ISSUE THREAD

**Issue by sinedoOo** [jaesung2061/anvel#8]
I was looking for good starter kit for Angular 2 and Lumen, and this is just brilliant. But could you upgrade the core packages? Final Angular 2.0 is out, Lumen 5.3 is ready.

**Comment by jaesung2061** [comment]
Sure, I've been really busy lately but I'll see if I can upgrade it this weekend.

**Comment by jaesung2061** [comment]
Version 2.0.0 is ready to go with a new release (v0.3.0). I will be looking into Lumen 5.3 in a couple days.

**Comment by jaesung2061** [comment]
Project has been updated.
